### ISSUE TITLE
FHI Angular Highcharts: Auto-hide metadataButton on small screens

### ISSUE THREAD

**Issue by VillereV** [folkehelseinstituttet/Fhi.Frontend.Demo#812]
### Description

Provide an option to hide the metadataButton on smaller screen sizes. e.g. `metadataButton.autohideOnSmall`.

On mobile or narrow screens, displaying the metadataButton can clutter the interface and degrade usability. 

Currently, we have to implement hacks to achieve this behavior. A flag would make it easier to maintain a responsive UI without resorting to custom code.

### Acceptance Criteria

Option to hide metadataButton on small screen sizes.

### Additional information

Workarounds/hacks:
**CSS**
Find the element to hide with css selectors.
```scss
// e.g.
.fhi-diagram-controls > .d-flex.flex-wrap.me-3 > .mb-3 {
    display: none;
}

@include media-breakpoint-up(md) {
    .fhi-diagram-controls > .d-flex.flex-wrap.me-3 > .mb-3 {
        display: block;
    }
}
```

**JavaScript**
Observe window size and set `DiagramOptions.controls.metadataButton.show` to `false` on small screen sizes.
